# https://dart.dev/tools/pub/pubspec
name: flutter_tilt
description: Easily apply tilt parallax hover effects for Flutter, which supports tilt, light, shadow effects, gyroscope sensors and many custom parameters.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://semver.org/spec/v2.0.0-rc.1.html
# https://dart.dev/tools/pub/versioning#semantic-versions
# https://dart.dev/tools/pub/dependencies#version-constraints
version: 3.3.1
homepage: https://amoshuke.github.io/flutter_tilt_book
repository: https://github.com/fluttercandies/flutter_tilt
issue_tracker: https://github.com/fluttercandies/flutter_tilt/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  stream_transform: ^2.1.0
  sensors_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:

topics:
  - tilt
  - skew
  - parallax
  - sensor
  - widget

screenshots:
  - description: 'Example Preview GIF'
    path: README/preview2-small.gif
  - description: 'Example Preview GIF'
    path: README/preview5-small.gif
  - description: 'Example Preview GIF'
    path: README/preview3-small.gif